/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thadani' at '28/9/16 7:52 PM' with Gradle 2.14.1
 *
 * @author thadani, @date 28/9/16 7:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
